---
 - name: Install Apache Kafka
   hosts: kafka01
   become: True
   vars:
     kafka_tar_file: files/kafka_2.12-2.4.0.tgz
     dest_dir_install: /usr/local/kafka

   tasks:
     - name: ensure kafka directory exists
       file:
         path: "{{ dest_dir_install }}"
         state: directory

     - name: Extract {{ kafka_tar_file }} into {{ dest_dir_install }}
       unarchive:
         src: "{{ kafka_tar_file }}"
         dest: "{{ dest_dir_install }}"
         extra_opts: [--strip-components=1]
