- name: Install Apache Kafka 
  hosts: kafka_nodes

  pre_tasks:
    - name: Add mappings
      become: yes
      blockinfile:
        path: /etc/hosts
        block: |  
          {% for item in groups['kafka_nodes'] %}
            {{ hostvars[item].ansible_ssh_host }}   {{ item }}    
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"

 
    
  #roles:
  #  - name: kafka-cluster
  
  #post_tasks:
  #  - shell: echo 'I":" Beginning to configure web server..'