- name: Install Apache Kafka
  hosts: kafka_nodes

  pre_tasks:
    - name: Add mappings /etc/hosts
      become: yes
      blockinfile:
        path: /etc/hosts
        block: |
          {% for node in groups['kafka_nodes'] -%}
            {{ hostvars[node]['ansible_default_ipv4']['address'] }} {{ node }}
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
  
  #Start Role kafka-cluster
  roles:
    - name: kafka-cluster

  post_tasks:

    - name: Test01 - Create Topic
      shell: "./kafka-topics.sh --create \
        --zookeeper {% for node in groups[ kafka_cluster_group_hosts ] -%} \
        {{ node }}:2181{% if not loop.last %},{% endif %}{%- endfor %} --replication-factor 2 \
        --partitions 12 --topic SampleTopic"
      args:
        chdir: "{{ kafka_home_dir }}/bin"
      register: output
      run_once: true

    - debug:
        msg: "{{ output.stdout_lines }}"
      run_once: true
