- name: Install Apache Kafka 
  hosts: kafka_nodes

  pre_tasks:
    - name: Add mappings
      become: yes
      lineinfile:
         dest: /etc/hosts
         line: "{{ hostvars[item].ansible_ssh_host }} {{ item }}"
         state: present 
      with_items: 
        - "{{ groups['kafka_nodes'] }}"
       
    
  #roles:
  #  - name: kafka-cluster
  
  #post_tasks:
  #  - shell: echo 'I":" Beginning to configure web server..'