- name: Install Kafka Server
  hosts: kafka01

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes

  roles:
    - name: kafka-cluster