- name: Install Apache Kafka 
  hosts: kafka_nodes

  pre_tasks:
    - name: Install
      become: yes
      blockinfile:
        path: /etc/hosts
        block: |  
          {{ item }} {{ item }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      with_items: groups['kafka_nodes']

 
    
  #roles:
  #  - name: kafka-cluster
  
  #post_tasks:
  #  - shell: echo 'I":" Beginning to configure web server..'