- name: Install Apache Kafka 
  hosts: kafka_nodes

  pre_tasks:
    - name: Add mappings to /etc/hosts
      become: yes
      blockinfile:
        path: /etc/hosts
        block: |  
          {% for node in groups['kafka_nodes'] %}
          {{ hostvars[node].ansible_ssh_host }}   {{ node }}    
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ node }}"

 
    
  #roles:
  #  - name: kafka-cluster
  
  #post_tasks:
  #  - shell: echo 'I":" Beginning to configure web server..'