- name: Install Apache Kafka 
  hosts: kafka_nodes

  pre_tasks:
    - name: Add mappings
      become: yes
      blockinfile:
        path: /etc/hosts
        block: | 
            {{ item }} 
        #marker: "# {mark} ANSIBLE MANAGED BLOCK" 
            with_items: "{{ groups['kafka_nodes'] }}"
       
    
  #roles:
  #  - name: kafka-cluster
  
  #post_tasks:
  #  - shell: echo 'I":" Beginning to configure web server..'