- name: Install Apache Kafka 
  hosts: kafka_nodes

  pre_tasks:
    - name: Add mappings /etc/hosts
      become: yes
      blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars[item].ansible_ssh_host }} {{ item }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}" 
      with_items: 
        - "{{ groups['kafka_nodes'] }}"
       
    
  #roles:
  #  - name: kafka-cluster
  
  #post_tasks:
  #  - shell: echo 'I":" Beginning to configure web server..'