---
- name: Download {{ kafka_download_url }}/kafka/{{ kafka_version }}/kafka_{{ kafka_version_scala }}-{{ kafka_version }}.tgz...
  become: yes
  get_url:
    dest: "/tmp/kafka_{{ kafka_version_scala }}-{{ kafka_version }}.tgz"
    url: "{{ kafka_download_url }}/kafka/{{ kafka_version }}/\
      kafka_{{ kafka_version_scala }}-{{ kafka_version }}.tgz"
    mode: "0644"
- name: Create a {{ kafka_zookeeper_dataDir }} if it does not exist...
  become: yes
  file:
    path: "{{ kafka_zookeeper_dataDir }}"
    state: directory
    mode: "0755"
- name: Create a {{ kafka_home_dir }} if it does not exist...
  become: yes
  file:
    path: "{{ kafka_home_dir }}"
    state: directory
    mode: "0755"
- name: Unarchive...
  become: yes
  unarchive:
    remote_src: yes
    src: /tmp/kafka_{{ kafka_version_scala }}-{{ kafka_version }}.tgz
    dest: "{{ kafka_home_dir }}"
    extra_opts: [--strip-components=1]
