---
- name: Fetch kafka binary package
  become: yes
  get_url:
    dest: "/tmp/kafka_{{ kafka_version_scala }}-{{ kafka_version_kafka }}.tgz"
    url: "{{ kafka_apache_mirror }}/kafka/{{ kafka_version_kafka }}/\
      kafka_{{ kafka_version_scala }}-{{ kafka_version_kafka }}.tgz"