---
- name: Add Zookeeper SystemD script
  become: yes
  template:
    dest: /etc/systemd/system/zookeeper.service
    mode: u+rw,g+rw,o+r
    src: zookeeper.service.j2
  when: ansible_service_mgr == "systemd"

- name: Ensure Zookeeper is enabled for SystemD
  become: yes
  systemd:
    daemon_reload: yes
    name: zookeeper
    enabled: yes
  when: ansible_service_mgr == "systemd"